version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    image: app:django
    container_name: django_container
    command: python datacleaner/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'data-app-db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_PORT: '3306'
    volumes:
      - ./data/mysql/dbb:/var/lib/mysql
